#!/usr/bin/env python3
"""
launch_report.py — Landscape Researcher Report Launcher

Starts the preview HTTP server (if not already running) and opens the browser
to the correct report URL with a ?report= query parameter.

Usage:
    python3 skills/landscape-researcher/launch_report.py \
        --report-dir "market-landscape-20260316-1430" \
        --report-file "Platform Engineering Solutions - Market Landscape Report.md" \
        [--port 7788] \
        [--no-browser]
"""

import argparse
import json
import os
import pathlib
import socket
import subprocess
import sys
import time
import urllib.parse
import webbrowser


def find_workspace_root(start: pathlib.Path) -> pathlib.Path:
    """Walk up from start until we find a directory containing 'reports/'."""
    current = start.resolve()
    for _ in range(10):  # Safety: don't walk up more than 10 levels
        if (current / "reports").is_dir():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent
    raise RuntimeError(
        f"Could not find workspace root (directory containing 'reports/') "
        f"starting from {start}. Run this script from within the multi-ai-skills/ tree."
    )


def is_port_in_use(port: int) -> bool:
    """Return True if something is already listening on the given port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("localhost", port)) == 0


def start_server(reports_dir: pathlib.Path, port: int) -> None:
    """Start python3 -m http.server as a detached background daemon."""
    print(f"Starting HTTP server on port {port} (serving {reports_dir}) ...")
    subprocess.Popen(
        [sys.executable, "-m", "http.server", str(port), "--directory", str(reports_dir)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,  # Detach from parent process group
    )
    # Give the server a moment to bind
    time.sleep(1.2)
    if not is_port_in_use(port):
        raise RuntimeError(
            f"Server failed to start on port {port}. "
            f"Check that python3 -m http.server works in {reports_dir}."
        )
    print(f"Server running at http://localhost:{port}/")


def ensure_chart_data_skeleton(report_dir_path: pathlib.Path, report_file: str) -> None:
    """Create a skeleton chart-data.json in the report dir if one does not already exist.

    The consolidator (or user) should fill in the data arrays. Until then, preview.html
    falls back to the built-in Platform Engineering defaults.
    """
    chart_data_path = report_dir_path / "chart-data.json"
    if chart_data_path.exists():
        return  # Already present — don't overwrite consolidator output

    # Derive a short title from the report filename for placeholder text
    title = report_file.replace(" - Market Landscape Report.md", "").strip()

    skeleton = {
        "_note": (
            "Generated by launch_report.py. Fill in chart data arrays (or have the "
            "consolidator populate this file) to enable report-specific charts. "
            "Delete this file to revert to viewer defaults."
        ),
        "anchors": {
            "mq":   ["3A", "Primary 2\u00d72", "2x2"],
            "wave": ["3B", "Wave-Style", "Wave"],
            "vc":   ["3C", "Value Curve"],
        },
        "titles": {
            "mq":   f"3A-1 \u00b7 {title} Positioning Matrix",
            "mq_x": "\u2190 Low X-axis Concept         High X-axis Concept \u2192",
            "mq_y": "\u2190 Low Y-axis Concept         High Y-axis Concept \u2192",
            "gmq":  f"3A-2 \u00b7 Magic Quadrant \u2014 {title}",
            "wave": f"3B \u00b7 Wave-Style Assessment \u2014 {title}",
            "vc":   f"3C \u00b7 Blue Ocean Value Curve \u2014 {title}",
        },
        "mq_data": [],
        "mq_colors": {
            "Quadrant A": "#4f46e5",
            "Quadrant B": "#059669",
            "Quadrant C": "#d97706",
            "Quadrant D": "#94a3b8",
        },
        "gmq_data": [],
        "gmq_colors": {
            "Leaders":      "#4f46e5",
            "Challengers":  "#7c3aed",
            "Visionaries":  "#d97706",
            "Niche Players":"#94a3b8",
        },
        "wave_data": [],
        "vc_kcfs": [],
        "vc_commercial": [],
        "vc_oss": [],
        "link_pairs": [],
    }
    with open(chart_data_path, "w", encoding="utf-8") as f:
        json.dump(skeleton, f, indent=2, ensure_ascii=False)
    print(f"  Created skeleton chart-data.json → {chart_data_path}")
    print(f"  Populate the data arrays to enable report-specific charts.")


def build_url(port: int, report_dir: str, report_file: str) -> str:
    """Build the preview URL with the ?report= query parameter."""
    # URL-encode the combined path (handles spaces and special chars in filenames)
    report_path = f"{report_dir}/{report_file}"
    encoded_path = urllib.parse.quote(report_path, safe="/")
    return f"http://localhost:{port}/preview.html?report={encoded_path}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Start the preview server and open the report in the browser."
    )
    parser.add_argument(
        "--report-dir",
        required=True,
        help="Subdirectory under reports/ containing the report "
             "(e.g., 'market-landscape-20260316-1430')",
    )
    parser.add_argument(
        "--report-file",
        required=True,
        help="Report filename (e.g., 'Platform Engineering Solutions - Market Landscape Report.md')",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=7788,
        help="HTTP server port (default: 7788)",
    )
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Print the URL but do not open the browser",
    )
    args = parser.parse_args()

    # Resolve workspace root
    script_dir = pathlib.Path(__file__).parent
    workspace_root = find_workspace_root(script_dir)
    reports_dir = workspace_root / "reports"

    # Verify the report file actually exists
    report_path = reports_dir / args.report_dir / args.report_file
    if not report_path.exists():
        print(
            f"WARNING: Report file not found at {report_path}\n"
            f"The server will still start, but the report may not load correctly.",
            file=sys.stderr,
        )

    # Create skeleton chart-data.json alongside the report (if not already present)
    ensure_chart_data_skeleton(reports_dir / args.report_dir, args.report_file)

    # Start server if port is not already in use
    if is_port_in_use(args.port):
        print(f"Port {args.port} already in use — assuming server is running.")
    else:
        start_server(reports_dir, args.port)

    # Build and output the URL
    url = build_url(args.port, args.report_dir, args.report_file)
    print(f"\n{'='*60}")
    print(f"  Report URL:")
    print(f"  {url}")
    print(f"{'='*60}\n")

    # Open the browser
    if not args.no_browser:
        print("Opening browser ...")
        webbrowser.open(url)


if __name__ == "__main__":
    main()
